sonar.projectKey=Hgyuxix_technova-inventory
sonar.organization=hgyuxix
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=venv/**,.github/**
sonar.tests=.
sonar.test.inclusions=test_app.py
sonar.coverage.exclusions=test_app.py